#!/usr/bin/env bash
# Transfers a file with scp
if [[ "$#" -lt 3 ]]; then
	echo Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
else	
	scp -i "$4" -o "StrictHostKeyChecking=no" "$3"@"$2":"$1" ~/
fi
