#!/usr/bin/env bash
# Sets up a brand new nginx server with a redirect page.
sudo apt-get -y nginx
sudo service nginx start
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
grep -q rewrite /etc/nginx/sites-available/default
if [[ !"$?" -eq 0 ]]; then
	sudo sed -i '26s/^/        rewrite ^\/redirect_me/ http:\/\/ianxaunliu-johnston.com permanent\;\n/' /etc/nginx/sites-available/default 
fi
sudo service nginx restart 
