#!/usr/bin/env bash
# Sets up a brand new nginx server with a redirect page.
sudo apt-get -y nginx
sudo service nginx start
sudo touch /usr/share/nginx/redirect_me
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
sudo sed -i '26s/^/        rewrite ^\/redirect_me$ http:\/\/ianxaunliu-johnston.com redirect\;\n/' /etc/nginx/sites-available/default 
sudo service nginx restart 
