#!/usr/bin/env bash
# Sets up a brand new nginx server with a redirect page.
sudo apt-get update
sudo apt-get install -y nginx
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
sudo sed -i '26s/^/        rewrite ^\/redirect_me\/ http:\/\/ianxaunliu-johnston.com permanent\;\n/' /etc/nginx/sites-available/default 
sudo sed -i '27s/^/        error_page 404 404.html\n/' /etc/nginx/sites-available/default 
sudo service nginx start 
