#!/usr/bin/env bash
# Fixes server
pkill apache2
sed -i -e 's#listen 80#listen 8080#' -e 's#listen \[::\]:80#listen \[::\]:8080#' /etc/nginx/sites-available/default
chown -R nginx:nginx /etc/nginx/
sed -i -e 's|#user www-data|user nginx|' /etc/nginx/nginx.conf
service nginx restart
