#!/bin/bash
total 92
drwxrwxr-x 2 vagrant vagrant 4096 Oct  4 19:02 .
drwxrwxr-x 4 vagrant vagrant 4096 Oct  4 17:34 ..
-rwxrw-r-- 1 vagrant vagrant   12 Oct  4 18:59 0~
-rwxrw-r-- 1 vagrant vagrant   16 Oct  4 19:01 0-current_working_directory
-rwxrw-r-- 1 vagrant vagrant   12 Oct  4 19:00 10-back
-rwxrw-r-- 1 vagrant vagrant   12 Oct  4 19:00 11-lists
-rwxrw-r-- 1 vagrant vagrant   12 Oct  4 19:00 12-file_type
-rwxrw-r-- 1 vagrant vagrant   12 Oct  4 19:00 13-symbolic_link
-rwxrw-r-- 1 vagrant vagrant   12 Oct  4 19:00 14-copy_html
-rwxrw-r-- 1 vagrant vagrant   12 Oct  4 19:00 15-lets_move
-rwxrw-r-- 1 vagrant vagrant   12 Oct  4 19:01 16-clean_emacs
-rwxrw-r-- 1 vagrant vagrant   12 Oct  4 19:01 17-tree
-rwxrw-r-- 1 vagrant vagrant   12 Oct  4 19:01 18-commas
-rwxrw-r-- 1 vagrant vagrant   15 Oct  4 19:01 1-listit
-rwxrw-r-- 1 vagrant vagrant   20 Oct  4 19:03 2-bring_me_home
-rwxrw-r-- 1 vagrant vagrant   18 Oct  4 19:03 3-listfiles
-rwxrw-r-- 1 vagrant vagrant   12 Oct  4 18:59 4-listmorefiles
-rwxrw-r-- 1 vagrant vagrant   12 Oct  4 19:00 5-listfilesdigitonly
-rwxrw-r-- 1 vagrant vagrant   12 Oct  4 19:00 6-firstdirectory
-rwxrw-r-- 1 vagrant vagrant   12 Oct  4 19:00 7-movethatfile
-rwxrw-r-- 1 vagrant vagrant   12 Oct  4 19:00 8-firstdelete
-rwxrw-r-- 1 vagrant vagrant   12 Oct  4 19:00 9-firstdirdeletion
-rw-rw-r-- 1 vagrant vagrant 1631 Oct  4 17:52 README.md
