#!/usr/bin/env bash
#Prints Holberton School to stdout in a while loop from 1-10. On the 4th loop, prints good luck. On the 8th, prints bad luck
i=1
while ((i <= 10)); do
	if [ "$i" == 4 ]; then
		echo bad luck
	elif [ "$i" == 8 ]; then
		echo good luck
	else
		echo Holberton School
	fi
	i=$((i+1))
done
