#!/usr/bin/env bash
# displays the contents of the current directory in a list format where only part of the first name after the first dash is displayed
for FILE in *; do
	echo "$FILE" | cut -d '-' -f2
done
