#!/usr/bin/env bash
#Prints a story about the /etc/passwd file contents:
##The user root is part of the USERNAME gang, lives in HOME_DIRECTORY and rides COMMAND/SHELL. USER ID's place is protected by the passcode PASSWORD, more info about the user here: USER ID INFO
while read -r; do 
	for ((i=1; i<8; i++)); do
		F[$i]=$(echo -e -n "$REPLY" | cut -d ':' -f $i)
	done
	echo "The user ${F[1]} is part of the ${F[4]} gang, lives in ${F[6]} and rides ${F[7]}. ${F[3]}'s place is protected by the passcode ${F[2]}, more info about the user here: ${F[5]}"
	
done < /etc/passwd

