#!/usr/bin/env bash
#Prints 1-20 to stdout using a while loop. Prints something unique on the 4th, 9th and 17th iterations
i=1
while ((i <= 20)); do
	echo $i
	case "$i" in
		4) echo bad luck from China
			;;
		9) echo bad luck from Japan
			;;
		17) echo bad luck from Italy
			;;
	esac
	i=$((i+1))
done
